### ISSUE TITLE
use your library as base to implement v2 registry p2p, came into a issue. could you please do me a favor

### ISSUE THREAD

**Issue by xiaods** [bobrik/bay#1]
our repo:
https://github.com/Dataman-Cloud/p2pull

tracker raise error:

```
===>P2 Docker Pull Tracker
2015/09/19 19:03:13 Listening for peers on port: 7788
2015/09/19 19:03:19 dealing with https://index.alauda.cn/v1/repositories/library/busybox/images
2015/09/19 19:03:19 t.flags: &{Port:7788 FileDir:/tmp SeedRatio:+Inf UseDeadlockDetector:true UseLPD:false UseDHT:false UseUPnP:false UseNATPMP:false TrackerlessMode:false ExecOnSeeding: Dial:<nil> Gateway: FileSystemProvider:<nil> InitialCheck:false Cacher:<nil> QuickResume:false MaxActive:0}
2015/09/19 19:03:19 tf:  /tmp/349100f032e80cca3daadd1c1c0950203faeacf6.torrent
2015/09/19 19:03:19 uint16(t.port) 7788
2015/09/19 19:03:19 [ 349100f032e80cca3daadd1c1c0950203faeacf6 ] Tracker: [], Comment: , InfoHash: bc4c3c47b1310efd75815ac42b90a9b44d3cc21d, Encoding: , Private: 0
2015/09/19 19:03:19 http: panic serving 10.3.11.3:39927: runtime error: invalid memory address or nil pointer dereference
goroutine 14 [running]:
net/http.func·011()
    /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/jackpal/Taipei-Torrent/torrent.(*TorrentSession).load(0xc208066200, 0x0, 0x0)
    /root/go/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:234 +0x64b
github.com/jackpal/Taipei-Torrent/torrent.NewTorrentSession(0xc208068120, 0xc208056a40, 0x35, 0xc208021e6c, 0x0, 0x0, 0x0)
    /root/go/src/github.com/jackpal/Taipei-Torrent/torrent/torrent.go:187 +0x886
main.(*Tracker).handleSafely(0xc2080681b0, 0x7f24cc919600, 0xc2080463c0, 0xc208056980, 0x3e, 0x0, 0x0)
    /root/p2pull/bay/tracker/tracker.go:127 +0x550
main.(*Tracker).handle(0xc2080681b0, 0x7f24cc919600, 0xc2080463c0, 0xc208034d00)
    /root/p2pull/bay/tracker/tracker.go:170 +0x4c7
main.*Tracker.(main.handle)·fm(0x7f24cc919600, 0xc2080463c0, 0xc208034d00)
    /root/p2pull/bay/tracker/tracker.go:74 +0x45
net/http.HandlerFunc.ServeHTTP(0xc20802aae0, 0x7f24cc919600, 0xc2080463c0, 0xc208034d00)
    /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20803d350, 0x7f24cc919600, 0xc2080463c0, 0xc208034d00)
    /usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc20805e300, 0x7f24cc919600, 0xc2080463c0, 0xc208034d00)
    /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208046320)
    /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1751 +0x35e
```

**Comment by xiaods** [comment]
i have fix it.

https://github.com/Dataman-Cloud/p2pull/pull/19/files
